########################################################
##               MASTER and BETA BUILD                ##
########################################################
- 
  branches:
    only:
      - master
      - beta
  version: version-placeholder-{build}-{branch}
  cache:
    - packages -> **\packages.config
  configuration: Release 
  environment:
    strong_name_key_secret:
      secure: klTrmUGElJ32M1IvA5ecksVOZoUhA22ZAEVhpi5qaZY=
  install:
    - git submodule update --init --recursive
    - nuget install secure-file -ExcludeVersion
    - secure-file\tools\secure-file -decrypt signingkey.snk.enc -secret %strong_name_key_secret%
  before_build:
  - ps: >-
      .\appveyor-deploy\MoveSigningKey.ps1 -signingKeyPath "$env:APPVEYOR_BUILD_FOLDER\signingkey.snk" -signingKeyDestination "C:\Keys\signingkey.snk";
      .\appveyor-deploy\NugetRestore.ps1;
      .\appveyor-deploy\AssemblyInfoVersionPatcher.ps1 -assemblyInfoPath  ".\SharedAssemblyInfo.cs"; 
      .\appveyor-deploy\BuildPreamble.ps1   
  build:
    verbosity: minimal  
  after_build:
  - ps: >-
      .\appveyor-deploy\NuspecVersionPatcher.ps1 -assembly "Difi.Felles.Utility\bin\Release\Difi.Felles.Utility.dll" -nuspec "difi-felles-utility.nuspec";
      nuget pack;
  artifacts:
    - path: '*.nupkg'
  before_test:
  - ps: >-
      .\appveyor-deploy\TestPreamble.ps1
  before_deploy:
  - ps: >-
      .\appveyor-deploy\DeployPreamble.ps1
  deploy:
    provider: NuGet
    api_key:
      secure: +8+b2Za0o/0TBgODNtnUXefTf/hhi79B0zGK7jfKQMOi8Uqs6QF0ojJyZHOkn25i
    skip_symbols: true
    artifact: /.*\.nupkg/


########################################################
##                    OTHER BRANCHES                  ##
########################################################

-
  version: version-placeholder-{build}-{branch}
  cache:
    - packages -> **\packages.config
  configuration: Release 
  environment:
    strong_name_key_secret:
      secure: klTrmUGElJ32M1IvA5ecksVOZoUhA22ZAEVhpi5qaZY=
  install:
    - git submodule update --init --recursive
    - nuget install secure-file -ExcludeVersion
    - secure-file\tools\secure-file -decrypt signingkey.snk.enc -secret %strong_name_key_secret%
  before_build:
  - ps: >-
      .\appveyor-deploy\MoveSigningKey.ps1 -signingKeyPath "$env:APPVEYOR_BUILD_FOLDER\signingkey.snk" -signingKeyDestination "C:\Keys\signingkey.snk";
      .\appveyor-deploy\NugetRestore.ps1;
      .\appveyor-deploy\BuildPreamble.ps1          
  build:
    verbosity: minimal  
  before_test:
  - ps: >-
      .\appveyor-deploy\TestPreamble.ps1